title: Gabriele Lo Cascio
subtitle: Labor improbus vincit omnia
description: "B.Sc. student in Innovation Engineering @ Università degli Studi di Palermo" # this means to ignore newlines until "baseurl:"

url: "" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

# Navigation
urls:
    # - text: Home
    #   url: /
    - text: About Me
      url: /about
    - text: Blog
      url: /blog
    # - text: Contact
    #   url : /contact


# Edit Author details (For multi authors check _data/authors.yml)

author_logo: profile.png
author: Gabriele Lo Cascio
author_bio: >
  Passionate self-learner with a knack for dissecting the world around me. Constantly pushing boundaries by building projects from scratch and embracing new challenges.

  <ul>
    <li>🧠 I'm particularly interested in AI and Machine Learning</li>
    <li>🏎 Formula SAE Team IT Member as Embedded Software Developer <a href="https://github.com/Formula-SAE/IT">Apex Corse</a></li>
    <li>⚛ <a href="https://qiskitfallfest23-unipa.github.io/">Qiskit Fall Fest 2023</a> Organizer</li>
    <li>👨🏻‍💻 Contributed to <a href="http://github.com/VivIngInf/VivereKaffettino">VivereKaffettino</a></li>
    <li>🎙️ I co-host the podcast <a href="https://open.spotify.com/episode/5usKggIh03yIwrXTdahqjZ?si=9c5d1ed64a5a469e">Iperconnessi</a> on Open Radio Unipa</li>
  </ul>
author_location: Italy
# author_website_url: "https://sujaykundu.com"
typewrite-text: Labor improbus vincit omnia
hero_cover_img: sample_cover.jpg # replace this for changing homepage cover (eg. try cover.jpeg). Image should be in /assets/img

# Experiences
author_work_experiences:
            - company_name: Apex Corse
              company_logo: apex.png
              company_url: https://www.apexcorse.it/
              designation: Software Engineer
              description: >
                <ul>
                    <li>Developed and implemented Telegram bots for automating internal processes, enhancing team efficiency</li>
                    <li>Assembled and maintained computer systems, ensuring optimal performance and reliability</li>
                    <li>Designed the team’s website with WordPress, ensuring a user‑friendly interface and seamless functionality</li>
                </ul>
              visibility: true

            - company_name: Duecci Market S.R.L.S
              company_logo: duecci.png
              company_url: https://www.crai-supermercati.it/punto-vendita/5693-cuor-di-crai-partanna-mondello/
              designation: Software Engineer & Techincal Support
              description: >
                <ul>
                    <li>Designed and implemented a Windows application for Accounting Management, result in a 30% reduction in data processing time and a 20% increase in overall efficiency</li>
                    <li>Developed an Android application for Invoice and Products Management, contributing to a streamlined process that increased productivity and reduced errors by 15%</li>
                    <li>Established a video surveillance system by configuring an NVR, enhancing security measures and reducing incidents by 30%</li>
                    <li>Produced impactful flyers and promotional images, leading to a 40% increase in engagement and visibility</li>
                </ul>
              visibility: true


# Education
author_education_details:
              - college_logo: unipa.png
                college_name: Università degli Studi di Palermo
                college_url: https://unipa.it
                college_degree: BSc student in Innovation Engineering
                description: >
                    <ul>
                      <li>Pursuing a comprehensive curriculum focusing on hybrid skills including Informatics, Statistics, Management, and Finance</li>
                      <li>Actively engaged in coursework aimed at developing proficiency in data engineering and data science</li>
                      <li>Established a video surveillance system by configuring an NVR, enhancing security measures and reducing incidents by 30%</li>
                      <li>Participating in hands‑on projects and practical assignments to apply theoretical knowledge to real‑world scenarios</li>
                    </ul>
                visibility: true

# Projects
author_project_details:

              - project_thumbnail: mdw_emotion.jpg
                project_title: MDW Emotion Detection Challenge - First Place
                project_description: >
                  <ul>
                    <li>Developed a machine learning solution by extracting semantic insights from tweets using an embedded model.</li>
                    <li>Enhanced data were then fed into a Voting classifier combining Random Forest, Logistic Regression, and Gradient Boosting.</li>
                    <li>Repository available <a href="https://github.com/Gabro29/MDWHack">here</a>.</li>
                  </ul>
                visibility: true

              - project_thumbnail: itadatahack.jpg
                project_title: ITADATAhack - Second Place
                project_description: >
                  <ul>
                    <li>Competed in a machine learning hackathon to predict customer creditworthiness.</li>
                    <li>Built a Voting classifier with eight Random Forest models, each trained on a different under-sampled subsample.</li>
                    <li>Repository available <a href="https://github.com/Gabro29/ITA_DATA_HACK">here</a>.</li>
                  </ul>
                visibility: true

              - project_thumbnail: podcast.png
                project_title: AI & Machine Learning Podcast
                project_description: >
                  <ul>
                    <li>Co‑host a podcast focused on AI and Machine Learning, discussing the latest trends, research, and applications in the field</li>
                    <li>Interview experts to provide listeners with valuable insights and diverse perspectives on AI advancements</li>
                    <li>Fostered a growing community of listeners interested in AI, technology, and innovation</li>
                  </ul>
                project_url: https://www.youtube.com/@iperconnessi
                visibility: true

              - project_thumbnail: qiskit_micio.png
                project_title: Qiskit Fall Fest
                project_description: >
                  <ul>
                    <li>Orchestrated the planning and execution of autonomous gatherings for Qiskit Fall Fest, a global initiative supported by IBM Quantum, enhancing teamwork skills and fostering active contributions to event strategy</li>
                  </ul>
                project_url: https://qiskitfallfest23-unipa.github.io/
                visibility: true

              - project_thumbnail: tic_tac_toe.png
                project_title: Tic-Tac-Toe Solved with Q-Learning
                project_description: >
                  <ul>
                    <li>Developed a Tic-Tac-Toe AI using Q-learning to improve gameplay over episodes.</li>
                    <li>The computer learns optimal moves by tracking rewards and updating a Q-table with board states.</li>
                    <li>Utilizes Python libraries such as NumPy and Matplotlib for calculations and visualizations.</li>
                    <li>Implemented an epsilon-greedy strategy for balanced exploration and exploitation, with dynamic Q-value updates.</li>
                    <li>Saved training progress for the AI through Q-table files, allowing for resumed learning.</li>
                  </ul>
                visibility: true

              - project_thumbnail: rubik.webp
                project_title: Brute Force a Rubik Cube
                project_description: >
                  <ul>
                    <li>Developed a Python script using Pygame and OpenGL to create an interactive virtual Rubik’s Cube</li>
                    <li>Implemented all possible moves and camera controls, enhancing user interactivity and visualization.</li>
                    <li>Open‑sourced the project, encouraging contributions and further development, including potential AI integration for solving the Rubik’s Cube</li>
                  </ul>
                project_url: https://github.com/Gabro29/Rubik
                visibility: true

              - project_thumbnail: conan.jpg
                project_title: Android Application with Kivy
                project_description: >
                  <ul>
                    <li>Created an app to search and categorize episodes of the Detective Conan, with custom episode descriptions and keyword‑based searches</li>
                    <li>Added features for generating random episodes and saving favorites, enhancing the viewing experience</li>
                    <li>Released the app without special permissions, making it easily accessible for users on various devices</li>
                  </ul>
                project_url: https://github.com/Gabro29/APTX
                visibility: true

              - project_thumbnail: accounting.webp
                project_title: Accounting Program
                project_description: Developed a desktop application for managing financial records. This project serves as a demonstration of key functionalities found in a more advanced and sophisticated software solution that I offer commercially.
                project_url: https://github.com/Gabro29/Accounting
                visibility: true

# social links
github_username:  gabro29
# linkedin_username: johndoe
instagram_username: ga8ro
youtube_username: UCkGvbGqYzDi3lfgtbQ_pngg
linkedin_username: gabriele-lo-cascio

# disqus_shortname: sujay-kundu
hyvor_talk_website_id: 476

# wakatime username (coding activity)
wakatime_username: gabro29

# mailchimp embedded form url (newsletter):
mailchimp_form_url: https://sujaykundu.us10.list-manage.com/subscribe/post?u=50bab1c85eae24ecfb0f68361&amp;id=3a2dd721d0

# contact form - (choose formspress or getform)
# getform_endpoint: 83b703c3-9e47-4df4-ac55-e24d7eb02abc
formspree_email: johndoe@gmail.com

# releases - widget can be (sidebar, modal or embed)
# olvy_organization: devlopr
# olvy_widget_type: sidebar

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true

# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'

collections:
  products:
    output: true
  authors:
    output: true

defaults:
  -
    scope:
      path: ""
      type: authors
    values:
      layout: author
      permalink: /blog/authors/:slug
  -
    scope:
      path: 'assets/**'
    values:
      sitemap: false

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-admin

# Jekyll Admin Config
jekyll_admin:
  # hidden_links:
  #   - posts
  #   - pages
  #   - staticfiles
  #   - datafiles
  #   - configuration
  homepage: "posts"


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.

### Switching Deployment Strategy (in DEPLOY_STRATEGY) file change the key accordingly:
# none - For no default
# gh-pages - For Github Pages
# firebase - For Firebase Hosting

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - assets/bower_components/isotope-layout/README.md
  - assets/bower_components/icono/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-svg-core/README.md
  - assets/bower_components/ghosthunter/README.md
  - assets/bower_components/nanobar/README.md
  - assets/bower_components/lightgallery/demo/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/free-brands-svg-icons/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/free-solid-svg-icons/README.md
  - assets/bower_components/jquery-mousewheel/README.md
  - assets/bower_components/get-size/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome/README.md
  - assets/bower_components/jquery-mousewheel/ChangeLog/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-regular/README.md
  - assets/bower_components/desandro-matches-selector/README.md
  - assets/bower_components/ev-emitter/README.md
  - assets/bower_components/font-awesome/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-solid/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-webfonts/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-brands/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-common-types/README.md
  - assets/bower_components/ghosthunter/example/Index.html
  - assets/bower_components/lightgallery/test/lightgallery.html
  - assets/bower_components/masonry-layout/README.md
  - assets/bower_components/imagesloaded/README.md


destination: ./build
